---
env:
  es2020: true
  browser: true
  node: true

extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react/recommended"
  - "prettier/@typescript-eslint"
  - "plugin:import/errors"
  - "plugin:import/warnings"
  - "plugin:import/typescript"

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 2020
  sourceType: "module"
  ecmaFeatures:
    jsx: true

plugins:
  - "react"
  - "react-hooks"
  - "@typescript-eslint"

rules:
  react-hooks/rules-of-hooks: "error"
  react-hooks/exhaustive-deps: "warn"
  no-console: warn
  no-multiple-empty-lines: error
  # Prevent relative imports above the current directory
  no-restricted-imports:
    - error
    - patterns: [../.*]
  # Prevent wildcards from being used
  import/no-namespace: error
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
      newlines-between: always
      alphabetize:
        order: asc
  import/newline-after-import:
    - error
    - count: 1

settings:
  react:
    version: "detect"
  import/resolver:
    node:
      paths:
        - "src"
