name: Configure Sentry and upload sourcemaps for a production release

on:
  push:
    branches: [production]

jobs:
  upload_sourcemaps:
    runs-on: ubuntu-latest
    env:
      REACT_APP_BUILD_ENV: production

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Set the version from package.json as an env variable
        run: |
          echo 'REACT_APP_VERSION'=$(node -p 'require("./package.json").version') >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      # Builds Dota Hero Hunt to get the source maps for Sentry
      - name: Build Dota Hero Hunt
        env:
          CI: false
        run: npm run build

      - name: Inform sentry of production release and upload sourcemaps
        uses: getsentry/action-release@v1.1.5
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: michaels-projects
          SENTRY_PROJECT: dota-hero-hunt
        with:
          environment: "production"
          finalize: true
          version: ${{ env.REACT_APP_VERSION }}
          sourcemaps: "./build/static/js/"
          url_prefix: "~/static/js"
